In [31]:
import pandas as pd
import numpy as np

df_08 = pd.read_excel('./xlsx/join_data_220801.xlsx')
df_08= df_08.set_index("DateTime")
df_ex = pd.read_excel('./xlsx/환율_220801.xlsx')
df_ex= df_ex.set_index("DateTime")

In [35]:
df= pd.concat([df_08, df_ex], axis=1)
df

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y,...,베이시스_10Y,Swap Point,ndf_mid,국고1년,국고3년,국고5년,국고10년,통안364일,통안2년,종가
DateTime,,,,,,,,,,,,,,,,,,,,,
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11,...,-53.5,-55,1303.30,2.92,3.08,3.13,3.18,3.00,3.07,1304.0
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04,...,-47.5,-55,1309.00,2.89,3.01,3.04,3.08,2.97,3.01,1304.7
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11,...,-41.5,-60,1315.00,2.90,3.06,3.10,3.13,2.97,3.08,1310.3
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03,...,-44.5,-55,1308.00,2.89,3.11,3.13,3.15,2.94,3.10,1310.1
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09,...,-50.5,-60,1302.75,2.87,3.07,3.09,3.12,2.89,3.07,1298.3
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02,...,-51.5,-60,1304.00,2.90,3.13,3.15,3.17,2.92,3.12,1306.4
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02,...,-51.5,-60,1300.50,2.89,3.13,3.15,3.16,2.91,3.11,1304.6
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00,...,-55.5,-60,1307.00,2.90,3.15,3.18,3.20,2.92,3.14,1310.4
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02,...,-54.5,-55,1297.00,2.89,3.12,3.17,3.21,2.90,3.12,1303.0
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03,...,-58.5,-60,1306.00,2.90,3.18,3.23,3.28,2.92,3.14,1302.4
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09,...,-52.5,-55,1313.50,2.86,3.07,3.12,3.15,2.86,3.04,1308.1
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07,...,-47.5,-55,1311.00,2.88,3.08,3.14,3.18,2.88,3.06,1310.3
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02,...,-51.5,-60,1314.70,2.88,3.12,3.18,3.22,2.90,3.08,1320.7
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03,...,-58.5,-50,1326.75,2.92,3.19,3.27,3.31,2.93,3.14,1325.9
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02,...,-59.5,-60,1335.40,2.96,3.24,3.31,3.34,2.85,3.19,1339.8
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03,...,-58.5,-55,1343.25,2.99,3.25,3.28,3.34,2.98,3.24,1345.5
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04,...,-64.5,-50,1339.00,3.04,3.31,3.39,3.43,3.03,3.28,1342.1
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22,...,-58.5,-45,1340.50,3.19,3.53,3.59,3.59,3.20,3.50,1335.2

In [36]:
df.isna().sum()

대비_irs_1Y     0
대비_irs_2Y     0
대비_irs_3Y     0
대비_irs_5Y     0
대비_irs_10Y    0
대비_crs_1Y     0
대비_crs_2Y     0
대비_crs_3Y     0
대비_crs_5Y     0
대비_crs_10Y    0
베이시스_1Y       0
베이시스_2Y       0
베이시스_3Y       0
베이시스_5Y       0
베이시스_10Y      0
Swap Point    0
ndf_mid       0
국고1년          0
국고3년          0
국고5년          0
국고10년         0
통안364일        0
통안2년          0
종가            0
dtype: int64

In [38]:
df.columns

Index(['대비_irs_1Y', '대비_irs_2Y', '대비_irs_3Y', '대비_irs_5Y', '대비_irs_10Y',
       '대비_crs_1Y', '대비_crs_2Y', '대비_crs_3Y', '대비_crs_5Y', '대비_crs_10Y',
       '베이시스_1Y', '베이시스_2Y', '베이시스_3Y', '베이시스_5Y', '베이시스_10Y', 'Swap Point',
       'ndf_mid', '국고1년', '국고3년', '국고5년', '국고10년', '통안364일', '통안2년', '종가'],
      dtype='object')

In [40]:

df['대비_국고_1Y'] = df['국고1년'] - df['국고1년'].shift(1)
df['대비_국고_3Y'] = df['국고3년'] - df['국고3년'].shift(1)
df['대비_국고_5Y'] = df['국고5년'] - df['국고5년'].shift(1)
df['대비_국고_10Y'] = df['국고10년']- df['국고10년'].shift(1)

df['대비_통안_1Y'] = df['통안364일'] - df['통안364일'].shift(1)
df['대비_통안_2Y'] = df['통안2년'] - df['통안2년'].shift(1)

df['스왑포인트_1M'] = df['Swap Point']/100 
df['전일종가_ex'] = df['종가'].shift(1)
df['종가_NDF_차이'] = df['전일종가_ex'] - df['ndf_mid']

In [51]:
df_ex_data=df[['대비_irs_1Y', '대비_irs_10Y', '대비_crs_1Y', '대비_crs_3Y', '대비_국고_5Y',
       '스왑포인트_1M', '전일종가_ex', '종가_NDF_차이']]
df_ex_target = df["종가"]

In [52]:
df_ex_data

,대비_irs_1Y,대비_irs_10Y,대비_crs_1Y,대비_crs_3Y,대비_국고_5Y,스왑포인트_1M,전일종가_ex,종가_NDF_차이
DateTime,,,,,,,,
2022-08-01,0.03,0.08,0.10,0.10,NaN,-0.55,NaN,NaN
2022-08-02,-0.03,-0.10,-0.02,-0.04,-0.09,-0.55,1304.0,-5.00
2022-08-03,0.03,0.05,0.04,0.10,0.06,-0.60,1304.7,-10.30
2022-08-04,0.01,0.06,0.04,0.04,0.03,-0.55,1310.3,2.30
2022-08-05,-0.02,-0.03,-0.05,-0.07,-0.04,-0.60,1310.1,7.35
2022-08-08,0.04,0.03,0.04,0.06,0.06,-0.60,1298.3,-5.70
2022-08-09,0.00,-0.02,0.08,0.00,0.00,-0.60,1306.4,5.90
2022-08-10,0.02,0.04,0.06,0.00,0.03,-0.60,1304.6,-2.40
2022-08-11,-0.02,0.01,0.00,0.01,-0.01,-0.55,1310.4,13.40
2022-08-12,0.02,0.07,-0.05,-0.02,0.06,-0.60,1303.0,-3.00
2022-08-16,-0.05,-0.15,0.00,-0.07,-0.11,-0.55,1302.4,-11.10
2022-08-17,0.01,0.02,0.04,0.04,0.02,-0.55,1308.1,-2.90
2022-08-18,0.00,0.06,-0.02,0.00,0.04,-0.60,1310.3,-4.40
2022-08-19,0.02,0.10,0.01,0.03,0.09,-0.50,1320.7,-6.05
2022-08-22,0.03,0.03,-0.02,0.03,0.04,-0.60,1325.9,-9.50
2022-08-23,0.05,0.02,-0.01,0.03,-0.03,-0.55,1339.8,-3.45
2022-08-24,0.05,0.10,0.01,0.04,0.11,-0.50,1345.5,6.50
2022-08-25,0.18,0.16,0.06,0.19,0.20,-0.45,1342.1,1.60

In [53]:



df_ex_data.feature = df_ex_data.columns 



df_scaled = pd.concat([df_ex_data, df_ex_target ], axis=1)
df_scaled

C:\Users\hyeok\AppData\Local\Temp\ipykernel_43544\2959378050.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_ex_data.feature = df_ex_data.columns

,대비_irs_1Y,대비_irs_10Y,대비_crs_1Y,대비_crs_3Y,대비_국고_5Y,스왑포인트_1M,전일종가_ex,종가_NDF_차이,종가
DateTime,,,,,,,,,
2022-08-01,0.03,0.08,0.10,0.10,NaN,-0.55,NaN,NaN,1304.0
2022-08-02,-0.03,-0.10,-0.02,-0.04,-0.09,-0.55,1304.0,-5.00,1304.7
2022-08-03,0.03,0.05,0.04,0.10,0.06,-0.60,1304.7,-10.30,1310.3
2022-08-04,0.01,0.06,0.04,0.04,0.03,-0.55,1310.3,2.30,1310.1
2022-08-05,-0.02,-0.03,-0.05,-0.07,-0.04,-0.60,1310.1,7.35,1298.3
2022-08-08,0.04,0.03,0.04,0.06,0.06,-0.60,1298.3,-5.70,1306.4
2022-08-09,0.00,-0.02,0.08,0.00,0.00,-0.60,1306.4,5.90,1304.6
2022-08-10,0.02,0.04,0.06,0.00,0.03,-0.60,1304.6,-2.40,1310.4
2022-08-11,-0.02,0.01,0.00,0.01,-0.01,-0.55,1310.4,13.40,1303.0
2022-08-12,0.02,0.07,-0.05,-0.02,0.06,-0.60,1303.0,-3.00,1302.4
2022-08-16,-0.05,-0.15,0.00,-0.07,-0.11,-0.55,1302.4,-11.10,1308.1
2022-08-17,0.01,0.02,0.04,0.04,0.02,-0.55,1308.1,-2.90,1310.3
2022-08-18,0.00,0.06,-0.02,0.00,0.04,-0.60,1310.3,-4.40,1320.7
2022-08-19,0.02,0.10,0.01,0.03,0.09,-0.50,1320.7,-6.05,1325.9
2022-08-22,0.03,0.03,-0.02,0.03,0.04,-0.60,1325.9,-9.50,1339.8
2022-08-23,0.05,0.02,-0.01,0.03,-0.03,-0.55,1339.8,-3.45,1345.5
2022-08-24,0.05,0.10,0.01,0.04,0.11,-0.50,1345.5,6.50,1342.1
2022-08-25,0.18,0.16,0.06,0.19,0.20,-0.45,1342.1,1.60,1335.2

In [42]:
df_scaled.columns

Index(['대비_irs_1Y', '대비_irs_10Y', '대비_crs_1Y', '대비_crs_3Y', '대비_국고_5Y',
       '스왑포인트_1M', '전일종가_ex', '종가_NDF_차이', '종가'],
      dtype='object')

In [54]:
train = df_scaled[0:18]
test = df_scaled[18:]

def make_dataset(data, label, window_size=5):
    feature_list = []
    label_list = []
    for i in range(len(data) - window_size):
        feature_list.append(np.array(data.iloc[i:i+window_size]))
        label_list.append(np.array(label.iloc[i+window_size]))
    return np.array(feature_list), np.array(label_list)

feature_cols = ['대비_irs_1Y', '대비_irs_10Y', '대비_crs_1Y', '대비_crs_3Y', '대비_국고_5Y',
       '스왑포인트_1M', '전일종가_ex', '종가_NDF_차이']
label_cols = ['종가']

In [55]:
from sklearn.model_selection import train_test_split

train_feature = train[feature_cols]
train_label = train[label_cols]
test_feature = test[feature_cols]
test_label = test[label_cols]

train_feature, train_label = make_dataset(train_feature, train_label, 5)
x_train, x_valid, y_train, y_valid = train_test_split(train_feature, train_label, test_size=0.2)
x_train.shape, x_valid.shape

((10, 5, 8), (3, 5, 8))

In [56]:
test_feature, test_label = make_dataset(test_feature, test_label, 5)
test_feature.shape, test_label.shape

((0,), (0,))

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.layers import LSTM

# 모델의 설정
model = Sequential()
model.add(LSTM(16, 
               input_shape=(train_feature.shape[1], train_feature.shape[2]), 
               activation='relu', 
               return_sequences=False)
          )
model.add(Dense(1))

# 모델의 컴파일(모델학습을 위한 학습과정 설정단계)
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mae'])
early_stop = EarlyStopping(monitor='val_loss', patience=10)
modelpath = './'
checkpoint = ModelCheckpoint(filepath=modelpath, monitor='val_loss', verbose=1, save_best_only=True, mode='auto')
# filename = os.path.join(file_path=model_path, 'tmp_checkpoint.h5')

# 모델의 실행
history = model.fit(x_train, y_train, 
                    epochs=200, 
                    batch_size=16,
                    validation_data=(x_valid, y_valid), 
                    callbacks=[early_stop, checkpoint])

# 테스트 정확도 출력                    
# print("\n Test Accuracy: %.4f" % model.evaluate(x_valid, y_valid))

Epoch 1/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 1: val_loss did not improve from inf
1/1 [==============================] - 2s 2s/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 2/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 2: val_loss did not improve from inf
1/1 [==============================] - 0s 30ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 3/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 3: val_loss did not improve from inf
1/1 [==============================] - 0s 33ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 4/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 4: val_loss did not improve from inf
1/1 [==============================] - 0s 36ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 5/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 5: val_loss did not improve from inf
1/1 [==============================] - 0s 36ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 6/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 6: val_loss did not improve from inf
1/1 [==============================] - 0s 35ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 7/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 7: val_loss did not improve from inf
1/1 [==============================] - 0s 34ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 8/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 8: val_loss did not improve from inf
1/1 [==============================] - 0s 36ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 9/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 9: val_loss did not improve from inf
1/1 [==============================] - 0s 38ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan
Epoch 10/200
1/1 [==============================] - ETA: 0s - loss: nan - mae: nan
Epoch 10: val_loss did not improve from inf
1/1 [==============================] - 0s 38ms/step - loss: nan - mae: nan - val_loss: nan - val_mae: nan