In [25]:
import pandas as pd
import numpy as np
# 데이터 불러오기
all = pd.read_excel("../데이터자료/Join_data.xlsx", index_col=0)

In [26]:
all.columns

Index(['DateTime', '종가_ex', '대비_ex', '증감률_ex', '1Y_Mid_irs', '1Y_전일비_irs',
       '2Y_Mid_irs', '2Y_전일비_irs', '3Y_Mid_irs', '3Y_전일비_irs', '5Y_Mid_irs',
       '5Y_전일비_irs', '10Y_Mid_irs', '10Y_전일비_irs', '1Y_Mid_crs', '1Y_전일비_crs',
       '2Y_Mid_crs', '2Y_전일비_crs', '3Y_Mid_crs', '3Y_전일비_crs', '5Y_Mid_crs',
       '5Y_전일비_crs', '10Y_Mid_crs', '10Y_전일비_crs', '국고1년', '국고3년', '국고5년',
       '국고10년', '통안364일', '통안2년', 'Bid_ndf', 'Ask_ndf', 'Mid_ndf', '전일비_ndf',
       '1Y_베이시스', '2Y_베이시스', '3Y_베이시스', '5Y_베이시스', '10Y_베이시스', 'M1_스왑포인트'],
      dtype='object')

In [27]:
all2 = all[[ '종가_ex', '1Y_Mid_irs', '2Y_Mid_irs',  '3Y_Mid_irs',  '5Y_Mid_irs', '10Y_Mid_irs', '1Y_Mid_crs','2Y_Mid_crs','3Y_Mid_crs', '5Y_Mid_crs',
             '10Y_Mid_crs','국고1년', '국고3년', '국고5년','국고10년', '통안364일', '통안2년',  'Mid_ndf',
             '1Y_베이시스', '2Y_베이시스', '3Y_베이시스', '5Y_베이시스', '10Y_베이시스']]
all2

,종가_ex,1Y_Mid_irs,2Y_Mid_irs,3Y_Mid_irs,5Y_Mid_irs,10Y_Mid_irs,1Y_Mid_crs,2Y_Mid_crs,3Y_Mid_crs,5Y_Mid_crs,...,국고5년,국고10년,통안364일,통안2년,Mid_ndf,1Y_베이시스,2Y_베이시스,3Y_베이시스,5Y_베이시스,10Y_베이시스
열1,,,,,,,,,,,,,,,,,,,,,
0,1126.5,2.850,2.740,2.740,2.770,2.910,2.09,1.815,1.81,1.72,...,3.14,3.14,2.80,2.83,1132.25,-76.0,-92.5,-93.0,-105.0,-108.0
1,1131.7,2.820,2.690,2.690,2.720,2.860,2.08,1.845,1.85,1.76,...,3.10,3.10,2.77,2.78,1134.00,-74.0,-84.5,-84.0,-96.0,-99.0
2,1134.8,2.790,2.660,2.660,2.690,2.840,2.07,1.830,1.83,1.68,...,3.03,3.03,2.75,2.77,1138.00,-72.0,-83.0,-83.0,-101.0,-112.0
3,1129.0,2.810,2.680,2.680,2.710,2.850,2.07,1.805,1.80,1.64,...,3.03,3.03,2.76,2.78,1128.50,-74.0,-87.5,-88.0,-107.0,-117.0
4,1128.8,2.820,2.680,2.680,2.720,2.870,2.09,1.820,1.80,1.57,...,3.03,3.03,2.75,2.77,1129.00,-73.0,-86.0,-88.0,-115.0,-127.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2455,1313.7,3.165,3.235,3.205,3.125,2.965,2.55,2.730,2.71,2.51,...,3.22,3.21,2.98,3.09,1309.85,-61.5,-50.5,-49.5,-61.5,-60.5
2456,1307.6,3.155,3.215,3.175,3.095,2.935,2.56,2.700,2.68,2.49,...,3.20,3.18,2.99,3.09,1311.00,-59.5,-51.5,-49.5,-60.5,-59.5
2457,1313.3,3.145,3.165,3.115,3.035,2.875,2.57,2.690,2.67,2.48,...,3.15,3.12,3.01,3.08,1310.50,-57.5,-47.5,-44.5,-55.5,-54.5
2458,1296.1,3.175,3.205,3.165,3.085,2.945,2.61,2.730,2.71,2.51,...,3.18,3.20,3.03,3.11,1306.00,-56.5,-47.5,-45.5,-57.5,-59.5
2459,1299.1,3.105,3.065,3.025,2.945,2.825,2.50,2.560,2.56,2.42,...,3.06,3.12,3.00,3.00,1295.75,-60.5,-50.5,-46.5,-52.5,-56.5

In [28]:
all_대비 = all2 - all2.shift(1)
all_대비 = all_대비.dropna()
all_대비 = all_대비.reset_index(drop = 'index')

In [29]:
#람다를 이용한 같은 글자 껴넣기
all_대비.rename(columns = lambda x: "대비_" + x, inplace = True)
all_대비

,대비_종가_ex,대비_1Y_Mid_irs,대비_2Y_Mid_irs,대비_3Y_Mid_irs,대비_5Y_Mid_irs,대비_10Y_Mid_irs,대비_1Y_Mid_crs,대비_2Y_Mid_crs,대비_3Y_Mid_crs,대비_5Y_Mid_crs,...,대비_국고5년,대비_국고10년,대비_통안364일,대비_통안2년,대비_Mid_ndf,대비_1Y_베이시스,대비_2Y_베이시스,대비_3Y_베이시스,대비_5Y_베이시스,대비_10Y_베이시스
0,5.2,-0.03,-0.05,-0.05,-0.05,-0.05,-0.01,0.030,0.04,0.04,...,-0.04,-0.04,-0.03,-0.05,1.75,2.0,8.0,9.0,9.0,9.0
1,3.1,-0.03,-0.03,-0.03,-0.03,-0.02,-0.01,-0.015,-0.02,-0.08,...,-0.07,-0.07,-0.02,-0.01,4.00,2.0,1.5,1.0,-5.0,-13.0
2,-5.8,0.02,0.02,0.02,0.02,0.01,0.00,-0.025,-0.03,-0.04,...,0.00,0.00,0.01,0.01,-9.50,-2.0,-4.5,-5.0,-6.0,-5.0
3,-0.2,0.01,0.00,0.00,0.01,0.02,0.02,0.015,0.00,-0.07,...,0.00,0.00,-0.01,-0.01,0.50,1.0,1.5,0.0,-8.0,-10.0
4,-0.5,0.01,0.02,0.02,0.02,0.03,0.01,0.000,0.00,-0.02,...,-0.02,-0.02,-0.01,-0.01,1.25,0.0,-2.0,-2.0,-4.0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,0.7,-0.04,-0.08,-0.07,-0.09,-0.11,-0.08,-0.090,-0.07,-0.11,...,-0.07,-0.09,-0.01,-0.05,3.35,-4.0,-1.0,0.0,-2.0,0.0
2455,-6.1,-0.01,-0.02,-0.03,-0.03,-0.03,0.01,-0.030,-0.03,-0.02,...,-0.02,-0.03,0.01,0.00,1.15,2.0,-1.0,0.0,1.0,1.0
2456,5.7,-0.01,-0.05,-0.06,-0.06,-0.06,0.01,-0.010,-0.01,-0.01,...,-0.05,-0.06,0.02,-0.01,-0.50,2.0,4.0,5.0,5.0,5.0
2457,-17.2,0.03,0.04,0.05,0.05,0.07,0.04,0.040,0.04,0.03,...,0.03,0.08,0.02,0.03,-4.50,1.0,0.0,-1.0,-2.0,-5.0
2458,3.0,-0.07,-0.14,-0.14,-0.14,-0.12,-0.11,-0.170,-0.15,-0.09,...,-0.12,-0.08,-0.03,-0.11,-10.25,-4.0,-3.0,-1.0,5.0,3.0

In [30]:
all_대비.columns = all_대비.columns.str.replace('Mid_','')
all_대비

,대비_종가_ex,대비_1Y_irs,대비_2Y_irs,대비_3Y_irs,대비_5Y_irs,대비_10Y_irs,대비_1Y_crs,대비_2Y_crs,대비_3Y_crs,대비_5Y_crs,...,대비_국고5년,대비_국고10년,대비_통안364일,대비_통안2년,대비_ndf,대비_1Y_베이시스,대비_2Y_베이시스,대비_3Y_베이시스,대비_5Y_베이시스,대비_10Y_베이시스
0,5.2,-0.03,-0.05,-0.05,-0.05,-0.05,-0.01,0.030,0.04,0.04,...,-0.04,-0.04,-0.03,-0.05,1.75,2.0,8.0,9.0,9.0,9.0
1,3.1,-0.03,-0.03,-0.03,-0.03,-0.02,-0.01,-0.015,-0.02,-0.08,...,-0.07,-0.07,-0.02,-0.01,4.00,2.0,1.5,1.0,-5.0,-13.0
2,-5.8,0.02,0.02,0.02,0.02,0.01,0.00,-0.025,-0.03,-0.04,...,0.00,0.00,0.01,0.01,-9.50,-2.0,-4.5,-5.0,-6.0,-5.0
3,-0.2,0.01,0.00,0.00,0.01,0.02,0.02,0.015,0.00,-0.07,...,0.00,0.00,-0.01,-0.01,0.50,1.0,1.5,0.0,-8.0,-10.0
4,-0.5,0.01,0.02,0.02,0.02,0.03,0.01,0.000,0.00,-0.02,...,-0.02,-0.02,-0.01,-0.01,1.25,0.0,-2.0,-2.0,-4.0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,0.7,-0.04,-0.08,-0.07,-0.09,-0.11,-0.08,-0.090,-0.07,-0.11,...,-0.07,-0.09,-0.01,-0.05,3.35,-4.0,-1.0,0.0,-2.0,0.0
2455,-6.1,-0.01,-0.02,-0.03,-0.03,-0.03,0.01,-0.030,-0.03,-0.02,...,-0.02,-0.03,0.01,0.00,1.15,2.0,-1.0,0.0,1.0,1.0
2456,5.7,-0.01,-0.05,-0.06,-0.06,-0.06,0.01,-0.010,-0.01,-0.01,...,-0.05,-0.06,0.02,-0.01,-0.50,2.0,4.0,5.0,5.0,5.0
2457,-17.2,0.03,0.04,0.05,0.05,0.07,0.04,0.040,0.04,0.03,...,0.03,0.08,0.02,0.03,-4.50,1.0,0.0,-1.0,-2.0,-5.0
2458,3.0,-0.07,-0.14,-0.14,-0.14,-0.12,-0.11,-0.170,-0.15,-0.09,...,-0.12,-0.08,-0.03,-0.11,-10.25,-4.0,-3.0,-1.0,5.0,3.0

In [ ]:
# concat으로 한번에 합치기