In [70]:
import pandas as pd
import numpy as np

# 데이터 끌고오기 및 삭제
df = pd.read_excel("../데이터자료/join_data.xlsx")
df = df.drop(['Unnamed: 0'], axis=1)
df.columns

In [72]:
#스왑포인트 제외 파생컬럼(등락률) 생성

df["전일비_ex"] = (df["종가_ex"] - df["종가_ex"].shift(1)) / df["종가_ex"].shift(1)
df["전일비_1Y_irs"] = (df["1Y_Mid_irs"] - df["1Y_Mid_irs"].shift(1)) / df["1Y_Mid_irs"].shift(1)
df["전일비_2Y_irs"] = (df["2Y_Mid_irs"] - df["2Y_Mid_irs"].shift(1)) / df["2Y_Mid_irs"].shift(1)
df["전일비_3Y_irs"] = (df["3Y_Mid_irs"] - df["3Y_Mid_irs"].shift(1)) / df["3Y_Mid_irs"].shift(1)
df["전일비_5Y_irs"] = (df["5Y_Mid_irs"] - df["5Y_Mid_irs"].shift(1)) / df["5Y_Mid_irs"].shift(1)
df["전일비_10Y_irs"] = (df["10Y_Mid_irs"] - df["10Y_Mid_irs"].shift(1)) / df["10Y_Mid_irs"].shift(1)
df["전일비_1Y_crs"] = (df["1Y_Mid_crs"] - df["1Y_Mid_crs"].shift(1)) / df["1Y_Mid_crs"].shift(1)
df["전일비_2Y_crs"] = (df["2Y_Mid_crs"] - df["2Y_Mid_crs"].shift(1)) / df["2Y_Mid_crs"].shift(1)
df["전일비_3Y_crs"] = (df["3Y_Mid_crs"] - df["3Y_Mid_crs"].shift(1)) / df["3Y_Mid_crs"].shift(1)
df["전일비_5Y_crs"] = (df["5Y_Mid_crs"] - df["5Y_Mid_crs"].shift(1)) / df["5Y_Mid_crs"].shift(1)
df["전일비_10Y_crs"] = (df["10Y_Mid_crs"] - df["10Y_Mid_crs"].shift(1)) / df["1Y_Mid_crs"].shift(1)
df["전일비_국고1년"] = (df["국고1년"] - df["국고1년"].shift(1)) / df["국고1년"].shift(1)
df["전일비_국고3년"] = (df["국고3년"] - df["국고3년"].shift(1)) / df["국고3년"].shift(1)
df["전일비_국고5년"] = (df["국고5년"] - df["국고5년"].shift(1)) / df["국고5년"].shift(1)
df["전일비_국고10년"] = (df["국고10년"] - df["국고10년"].shift(1)) / df["국고10년"].shift(1)
df["전일비_통안364일"] = (df["통안364일"] - df["통안364일"].shift(1)) / df["통안364일"].shift(1)
df["전일비_통안2년"] = (df["통안2년"] - df["통안2년"].shift(1)) / df["통안2년"].shift(1)
df["전일비_1Y_베이시스"] = (df["1Y_베이시스"] - df["1Y_베이시스"].shift(1)) / df["1Y_베이시스"].shift(1)
df["전일비_2Y_베이시스"] = (df["2Y_베이시스"] - df["2Y_베이시스"].shift(1)) / df["2Y_베이시스"].shift(1)
df["전일비_3Y_베이시스"] = (df["3Y_베이시스"] - df["3Y_베이시스"].shift(1)) / df["3Y_베이시스"].shift(1)
df["전일비_5Y_베이시스"] = (df["5Y_베이시스"] - df["5Y_베이시스"].shift(1)) / df["5Y_베이시스"].shift(1)
df["전일비_10Y_베이시스"] = (df["10Y_베이시스"] - df["10Y_베이시스"].shift(1)) / df["10Y_베이시스"].shift(1)
df["전일비_ndf"] = (df["Mid_ndf"] - df["Mid_ndf"].shift(1)) / df["Mid_ndf"].shift(1)
df["M1_스왑포인트(원)"] = df["M1_스왑포인트"]/100 
df.head()

,DateTime,종가_ex,1Y_Mid_irs,2Y_Mid_irs,3Y_Mid_irs,5Y_Mid_irs,10Y_Mid_irs,1Y_Mid_crs,2Y_Mid_crs,3Y_Mid_crs,...,전일비_국고5년,전일비_국고10년,전일비_통안364일,전일비_통안2년,전일비_1Y_베이시스,전일비_2Y_베이시스,전일비_3Y_베이시스,전일비_5Y_베이시스,전일비_10Y_베이시스,M1_스왑포인트(원)
0,2012-08-01,1126.5,2.85,2.74,2.74,2.77,2.91,2.09,1.815,1.81,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.6
1,2012-08-02,1131.7,2.82,2.69,2.69,2.72,2.86,2.08,1.845,1.85,...,-0.012739,-0.012739,-0.010714,-0.017668,-0.026316,-0.086486,-0.096774,-0.085714,-0.083333,2.5
2,2012-08-03,1134.8,2.79,2.66,2.66,2.69,2.84,2.07,1.830,1.83,...,-0.022581,-0.022581,-0.007220,-0.003597,-0.027027,-0.017751,-0.011905,0.052083,0.131313,2.4
3,2012-08-06,1129.0,2.81,2.68,2.68,2.71,2.85,2.07,1.805,1.80,...,0.000000,0.000000,0.003636,0.003610,0.027778,0.054217,0.060241,0.059406,0.044643,2.4
4,2012-08-07,1128.8,2.82,2.68,2.68,2.72,2.87,2.09,1.820,1.80,...,0.000000,0.000000,-0.003623,-0.003597,-0.013514,-0.017143,-0.000000,0.074766,0.085470,2.5

In [73]:
df.iloc[1:]
df.reset_index(drop=True, inplace=True)
df[["전일비_10Y_crs","전일비_5Y_crs","전일비_1Y_crs"]]= df[["전일비_10Y_crs","전일비_5Y_crs","전일비_1Y_crs"]].fillna(0)
df["전일비_10Y_crs"][df["전일비_10Y_crs"].isnull()]

Series([], Name: 전일비_10Y_crs, dtype: float64)

In [74]:
# 등락률 중 분모에 0이들어가는 경우에 0이 2개연속이면 0 , 0이 전행에만 있는 경우이면 그 값을 그대로 넣어준다
for i in range(1, 2459):
    # "1Y_Mid_crs"
    if df.loc[i, "1Y_Mid_crs"] == 0 and df.loc[i-1,"1Y_Mid_crs"] == 0:
        df.loc[i,"전일비_1Y_crs"] = 0
    elif df.loc[i, "1Y_Mid_crs"] != 0 and df.loc[i-1,"1Y_Mid_crs"] == 0:
        df.loc[i,"전일비_1Y_crs"] = df.loc[i,"1Y_Mid_crs"]
        
    # "2Y_Mid_crs"  
    if df.loc[i, "2Y_Mid_crs"] == 0 and df.loc[i-1,"2Y_Mid_crs"] == 0:
        df.loc[i,"전일비_2Y_crs"] = 0
    elif df.loc[i, "2Y_Mid_crs"] != 0 and df.loc[i-1,"2Y_Mid_crs"] == 0:
        df.loc[i,"전일비_2Y_crs"] = df.loc[i,"2Y_Mid_crs"]
        
    # "3Y_Mid_crs" 
    if df.loc[i, "3Y_Mid_crs"] == 0 and df.loc[i-1,"3Y_Mid_crs"] == 0:
        df.loc[i,"전일비_3Y_crs"] = 0
    elif df.loc[i, "3Y_Mid_crs"] != 0 and df.loc[i-1,"3Y_Mid_crs"] == 0:
        df.loc[i,"전일비_3Y_crs"] = df.loc[i,"3Y_Mid_crs"]
        
    # "5Y_Mid_crs"   
    if df.loc[i, "5Y_Mid_crs"] == 0 and df.loc[i-1,"5Y_Mid_crs"] == 0:
        df.loc[i,"전일비_5Y_crs"] = 0
    elif df.loc[i, "5Y_Mid_crs"] != 0 and df.loc[i-1,"5Y_Mid_crs"] == 0:
        df.loc[i,"전일비_5Y_crs"] = df.loc[i,"5Y_Mid_crs"]
    
    # "10Y_Mid_crs"   
    if df.loc[i, "10Y_Mid_crs"] == 0 and df.loc[i-1,"10Y_Mid_crs"] == 0:
        df.loc[i,"전일비_10Y_crs"] = 0
    elif df.loc[i, "10Y_Mid_crs"] != 0 and df.loc[i-1,"10Y_Mid_crs"] == 0:
        df.loc[i,"전일비_10Y_crs"] = df.loc[i,"10Y_Mid_crs"]
        
    # "1Y_베이시스"   
    if df.loc[i, "1Y_베이시스"] == 0 and df.loc[i-1,"1Y_베이시스"] == 0:
        df.loc[i,"전일비_1Y_베이시스"] = 0
    elif df.loc[i, "1Y_베이시스"] != 0 and df.loc[i-1,"1Y_베이시스"] == 0:
        df.loc[i,"전일비_1Y_베이시스"] = df.loc[i,"1Y_베이시스"]
    
    # "2Y_베이시스"   
    if df.loc[i, "2Y_베이시스"] == 0 and df.loc[i-1,"2Y_베이시스"] == 0:
        df.loc[i,"전일비_2Y_베이시스"] = 0
    elif df.loc[i, "2Y_베이시스"] != 0 and df.loc[i-1,"2Y_베이시스"] == 0:
        df.loc[i,"전일비_2Y_베이시스"] = df.loc[i,"2Y_베이시스"]
    
    # "3Y_베이시스"            
    if df.loc[i, "3Y_베이시스"] == 0 and df.loc[i-1,"3Y_베이시스"] == 0:
        df.loc[i,"전일비_3Y_베이시스"] = 0
    elif df.loc[i, "3Y_베이시스"] != 0 and df.loc[i-1,"3Y_베이시스"] == 0:
        df.loc[i,"전일비_3Y_베이시스"] = df.loc[i,"3Y_베이시스"]            
     
    # "국고3년"    
    if df.loc[i, "국고3년"] == 0 and df.loc[i-1,"국고3년"] == 0:
        df.loc[i,"전일비_국고3년"] = 0
    elif df.loc[i, "국고3년"] != 0 and df.loc[i-1,"국고3년"] == 0:
        df.loc[i,"전일비_국고3년"] = df.loc[i,"국고3년"]
        
    # "통안364일"    
    if df.loc[i, "통안364일"] == 0 and df.loc[i-1,"통안364일"] == 0:
        df.loc[i,"전일비_통안364일"] = 0
    elif df.loc[i, "통안364일"] != 0 and df.loc[i-1,"통안364일"] == 0:
        df.loc[i,"전일비_통안364일"] = df.loc[i,"통안364일"]
    
    # "통안2년"    
    if df.loc[i, "통안2년"] == 0 and df.loc[i-1,"통안2년"] == 0:
        df.loc[i,"전일비_통안2년"] = 0
    elif df.loc[i, "통안2년"] != 0 and df.loc[i-1,"통안2년"] == 0:
        df.loc[i,"전일비_통안2년"] = df.loc[i,"통안2년"]

In [75]:
# 결측치 행 제거
df = df.dropna()

In [76]:
# 독립변수 종속변수 설정
# df_Data = df[["DateTime", '전일비_1Y_irs','전일비_2Y_irs', '전일비_3Y_irs', '전일비_5Y_irs', '전일비_10Y_irs', '전일비_1Y_crs',
#         '전일비_2Y_crs', '전일비_3Y_crs', '전일비_5Y_crs', '전일비_10Y_crs', '전일비_국고1년',
#        '전일비_국고3년', '전일비_국고5년', '전일비_국고10년', '전일비_통안364일', '전일비_통안2년',
#         '전일비_1Y_베이시스', '전일비_2Y_베이시스', '전일비_3Y_베이시스', '전일비_5Y_베이시스',
#         '전일비_10Y_베이시스', 'M1_스왑포인트(원)']]
# df_target = df['종가_ex']

In [77]:
df_Data = df[["DateTime", '전일비_10Y_crs']]
df_target = df['종가_ex']

In [78]:
# 스케일링전 데이터 전처리
df_Data=df_Data.round(4)
df_Data = df_Data.set_index("DateTime")
df_Data.feature= df_Data.columns
df_Data.feature

df_Data

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_26512\3198166078.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df_Data.feature= df_Data.columns

            전일비_10Y_crs
DateTime
2012-08-02       0.0191
2012-08-03      -0.0721
2012-08-06      -0.0193
2012-08-07      -0.0386
2012-08-08      -0.0191
...                 ...
2022-07-25      -0.0418
2022-07-26      -0.0078
2022-07-27      -0.0039
2022-07-28       0.0078
2022-07-29      -0.0345

[2459 rows x 1 columns]

In [79]:
# 스케일링 코드
from sklearn.preprocessing import StandardScaler, MinMaxScaler
scaler = StandardScaler()

scaler.fit(df_Data)
df_Data_scaled= scaler.transform(df_Data)
df_scaled = pd.DataFrame (data = df_Data_scaled, columns=df_Data.feature)
df_scaled.index = df_Data.index

c:\Users\tlsdm\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: Input X contains infinity or a value too large for dtype('float64').