In [77]:
import pandas as pd
import numpy as np

In [78]:
df_1 = pd.read_excel('./xlsx/220801/irs_220801.xlsx', index_col = 0)
df_2 = pd.read_excel('./xlsx/220801/crs_220801.xlsx', index_col = 0)
df_3 = pd.read_excel('./xlsx/220801/ndf_220801.xlsx', index_col = 0)
df_4 = pd.read_excel('./xlsx/220801/SwapBasis_220801.xlsx', index_col = 0)
df_5 = pd.read_excel('./xlsx/220801/SwapPoint_220801.xlsx', index_col = 0)
df_6 = pd.read_excel('./xlsx/220801/ktb_220801.xlsx', index_col = 0)

In [79]:
df_1

            대비_irs_1Y  대비_irs_2Y  대비_irs_3Y  대비_irs_5Y  대비_irs_10Y
DateTime
2022-08-26       0.01       0.02       0.02       0.03        0.01
2022-08-25       0.18       0.20       0.21       0.20        0.16
2022-08-24       0.05       0.07       0.07       0.08        0.10
2022-08-23       0.05       0.05       0.05       0.03        0.02
2022-08-22       0.03       0.04       0.05       0.05        0.03
2022-08-19       0.02       0.05       0.07       0.08        0.10
2022-08-18       0.00       0.05       0.04       0.05        0.06
2022-08-17       0.01       0.02       0.02       0.02        0.02
2022-08-16      -0.05      -0.11      -0.12      -0.14       -0.15
2022-08-12       0.02       0.04       0.05       0.06        0.07
2022-08-11      -0.02      -0.03      -0.02       0.00        0.01
2022-08-10       0.02       0.03       0.05       0.05        0.04
2022-08-09       0.00       0.02       0.00      -0.01       -0.02
2022-08-08       0.04       0.05       0.04       0.04        0.03
2022-08-05      -0.02      -0.04      -0.05      -0.04       -0.03
2022-08-04       0.01       0.06       0.06       0.06        0.06
2022-08-03       0.03       0.05       0.05       0.05        0.05
2022-08-02      -0.03      -0.08      -0.08      -0.09       -0.10
2022-08-01       0.03       0.07       0.06       0.06        0.08

In [80]:
df_2

            대비_crs_1Y  대비_crs_2Y  대비_crs_3Y  대비_crs_5Y  대비_crs_10Y
DateTime
2022-08-26       0.01       0.08       0.09       0.10        0.10
2022-08-25       0.06       0.16       0.19       0.22        0.22
2022-08-24       0.01       0.05       0.04       0.03        0.04
2022-08-23      -0.01       0.03       0.03       0.04        0.03
2022-08-22      -0.02       0.02       0.03       0.02        0.02
2022-08-19       0.01       0.03       0.03       0.04        0.03
2022-08-18      -0.02       0.00       0.00       0.01        0.02
2022-08-17       0.04       0.04       0.04       0.06        0.07
2022-08-16       0.00      -0.07      -0.07      -0.08       -0.09
2022-08-12      -0.05      -0.03      -0.02       0.02        0.03
2022-08-11       0.00       0.02       0.01       0.03        0.02
2022-08-10       0.06       0.00       0.00      -0.01        0.00
2022-08-09       0.08       0.03       0.00      -0.01       -0.02
2022-08-08       0.04       0.05       0.06       0.04        0.02
2022-08-05      -0.05      -0.06      -0.07      -0.08       -0.09
2022-08-04       0.04       0.02       0.04       0.03        0.03
2022-08-03       0.04       0.09       0.10       0.11        0.11
2022-08-02      -0.02      -0.04      -0.04      -0.03       -0.04
2022-08-01       0.10       0.09       0.10       0.10        0.11

In [81]:
df_3

            ndf_mid
DateTime
2022-08-26  1334.50
2022-08-25  1340.50
2022-08-24  1339.00
2022-08-23  1343.25
2022-08-22  1335.40
2022-08-20  1335.40
2022-08-19  1326.75
2022-08-18  1314.70
2022-08-17  1311.00
2022-08-16  1313.50
2022-08-13  1301.00
2022-08-12  1306.00
2022-08-11  1297.00
2022-08-10  1307.00
2022-08-09  1300.50
2022-08-08  1304.00
2022-08-06  1304.00
2022-08-05  1302.75
2022-08-04  1308.00
2022-08-03  1315.00
2022-08-02  1309.00
2022-08-01  1303.30

In [82]:
df_4

            베이시스_1Y  베이시스_2Y  베이시스_3Y  베이시스_5Y  베이시스_10Y
DateTime
2022-08-26    -66.5    -55.5    -47.5    -46.5     -49.5
2022-08-25    -66.5    -61.5    -54.5    -53.5     -58.5
2022-08-24    -54.5    -57.5    -52.5    -55.5     -64.5
2022-08-23    -50.5    -55.5    -49.5    -50.5     -58.5
2022-08-22    -44.5    -53.5    -47.5    -51.5     -59.5
2022-08-19    -39.5    -51.5    -45.5    -48.5     -58.5
2022-08-18    -38.5    -49.5    -41.5    -44.5     -51.5
2022-08-17    -36.5    -44.5    -37.5    -40.5     -47.5
2022-08-16    -39.5    -46.5    -39.5    -44.5     -52.5
2022-08-12    -44.5    -50.5    -44.5    -50.5     -58.5
2022-08-11    -37.5    -43.5    -37.5    -46.5     -54.5
2022-08-10    -39.5    -48.5    -40.5    -49.5     -55.5
2022-08-09    -43.5    -45.5    -35.5    -43.5     -51.5
2022-08-08    -51.5    -46.5    -35.5    -43.5     -51.5
2022-08-05    -51.5    -46.5    -37.5    -43.5     -50.5
2022-08-04    -48.5    -44.5    -35.5    -39.5     -44.5
2022-08-03    -51.5    -40.5    -33.5    -36.5     -41.5
2022-08-02    -52.5    -44.5    -38.5    -42.5     -47.5
2022-08-01    -53.5    -48.5    -42.5    -48.5     -53.5

In [83]:
df_5

            Swap Point
DateTime
2022-08-26         -50
2022-08-25         -45
2022-08-24         -50
2022-08-23         -55
2022-08-22         -60
2022-08-19         -50
2022-08-18         -60
2022-08-17         -55
2022-08-16         -55
2022-08-12         -60
2022-08-11         -55
2022-08-10         -60
2022-08-09         -60
2022-08-08         -60
2022-08-05         -60
2022-08-04         -55
2022-08-03         -60
2022-08-02         -55
2022-08-01         -55

In [84]:
df_6

            국고1년  국고3년  국고5년  통안364일  통안2년
DateTime
2022-08-01  2.92  3.08  3.13    3.00  3.07
2022-08-02  2.89  3.01  3.04    2.97  3.01
2022-08-03  2.90  3.06  3.10    2.97  3.08
2022-08-04  2.89  3.11  3.13    2.94  3.10
2022-08-05  2.87  3.07  3.09    2.89  3.07
2022-08-08  2.90  3.13  3.15    2.92  3.12
2022-08-09  2.89  3.13  3.15    2.91  3.11
2022-08-10  2.90  3.15  3.18    2.92  3.14
2022-08-11  2.89  3.12  3.17    2.90  3.12
2022-08-12  2.90  3.18  3.23    2.92  3.14
2022-08-16  2.86  3.07  3.12    2.86  3.04
2022-08-17  2.88  3.08  3.14    2.88  3.06
2022-08-18  2.88  3.12  3.18    2.90  3.08
2022-08-19  2.92  3.19  3.27    2.93  3.14
2022-08-22  2.96  3.24  3.31    2.85  3.19
2022-08-23  2.99  3.25  3.28    2.98  3.24
2022-08-24  3.04  3.31  3.39    3.03  3.28
2022-08-25  3.19  3.53  3.59    3.20  3.50

In [85]:
irscrs = pd.concat([df_1, df_2], axis=1)
irscrs

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y
DateTime,,,,,,,,,,
2022-08-26,0.01,0.02,0.02,0.03,0.01,0.01,0.08,0.09,0.10,0.10
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11

In [86]:
irscrsbasis = pd.concat([irscrs, df_4], axis=1)
irscrsbasis

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y,베이시스_1Y,베이시스_2Y,베이시스_3Y,베이시스_5Y,베이시스_10Y
DateTime,,,,,,,,,,,,,,,
2022-08-26,0.01,0.02,0.02,0.03,0.01,0.01,0.08,0.09,0.10,0.10,-66.5,-55.5,-47.5,-46.5,-49.5
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22,-66.5,-61.5,-54.5,-53.5,-58.5
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04,-54.5,-57.5,-52.5,-55.5,-64.5
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03,-50.5,-55.5,-49.5,-50.5,-58.5
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02,-44.5,-53.5,-47.5,-51.5,-59.5
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03,-39.5,-51.5,-45.5,-48.5,-58.5
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02,-38.5,-49.5,-41.5,-44.5,-51.5
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07,-36.5,-44.5,-37.5,-40.5,-47.5
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09,-39.5,-46.5,-39.5,-44.5,-52.5
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03,-44.5,-50.5,-44.5,-50.5,-58.5
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02,-37.5,-43.5,-37.5,-46.5,-54.5
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00,-39.5,-48.5,-40.5,-49.5,-55.5
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02,-43.5,-45.5,-35.5,-43.5,-51.5
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02,-51.5,-46.5,-35.5,-43.5,-51.5
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09,-51.5,-46.5,-37.5,-43.5,-50.5
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03,-48.5,-44.5,-35.5,-39.5,-44.5
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11,-51.5,-40.5,-33.5,-36.5,-41.5
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04,-52.5,-44.5,-38.5,-42.5,-47.5
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11,-53.5,-48.5,-42.5,-48.5,-53.5

In [87]:
irscrsbasis = pd.concat([irscrs, df_4], axis=1)
irscrsbasis

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y,베이시스_1Y,베이시스_2Y,베이시스_3Y,베이시스_5Y,베이시스_10Y
DateTime,,,,,,,,,,,,,,,
2022-08-26,0.01,0.02,0.02,0.03,0.01,0.01,0.08,0.09,0.10,0.10,-66.5,-55.5,-47.5,-46.5,-49.5
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22,-66.5,-61.5,-54.5,-53.5,-58.5
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04,-54.5,-57.5,-52.5,-55.5,-64.5
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03,-50.5,-55.5,-49.5,-50.5,-58.5
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02,-44.5,-53.5,-47.5,-51.5,-59.5
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03,-39.5,-51.5,-45.5,-48.5,-58.5
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02,-38.5,-49.5,-41.5,-44.5,-51.5
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07,-36.5,-44.5,-37.5,-40.5,-47.5
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09,-39.5,-46.5,-39.5,-44.5,-52.5
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03,-44.5,-50.5,-44.5,-50.5,-58.5
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02,-37.5,-43.5,-37.5,-46.5,-54.5
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00,-39.5,-48.5,-40.5,-49.5,-55.5
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02,-43.5,-45.5,-35.5,-43.5,-51.5
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02,-51.5,-46.5,-35.5,-43.5,-51.5
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09,-51.5,-46.5,-37.5,-43.5,-50.5
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03,-48.5,-44.5,-35.5,-39.5,-44.5
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11,-51.5,-40.5,-33.5,-36.5,-41.5
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04,-52.5,-44.5,-38.5,-42.5,-47.5
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11,-53.5,-48.5,-42.5,-48.5,-53.5

In [88]:
pointndf = pd.concat([df_5, df_3], axis=1)
pointndf

            Swap Point  ndf_mid
DateTime
2022-08-01       -55.0  1303.30
2022-08-02       -55.0  1309.00
2022-08-03       -60.0  1315.00
2022-08-04       -55.0  1308.00
2022-08-05       -60.0  1302.75
2022-08-06         NaN  1304.00
2022-08-08       -60.0  1304.00
2022-08-09       -60.0  1300.50
2022-08-10       -60.0  1307.00
2022-08-11       -55.0  1297.00
2022-08-12       -60.0  1306.00
2022-08-13         NaN  1301.00
2022-08-16       -55.0  1313.50
2022-08-17       -55.0  1311.00
2022-08-18       -60.0  1314.70
2022-08-19       -50.0  1326.75
2022-08-20         NaN  1335.40
2022-08-22       -60.0  1335.40
2022-08-23       -55.0  1343.25
2022-08-24       -50.0  1339.00
2022-08-25       -45.0  1340.50
2022-08-26       -50.0  1334.50

In [89]:
join = pd.concat([irscrsbasis , pointndf], axis=1)

In [90]:
join = join.dropna()

In [91]:
join = join.sort_index()

In [92]:
join

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y,베이시스_1Y,베이시스_2Y,베이시스_3Y,베이시스_5Y,베이시스_10Y,Swap Point,ndf_mid
DateTime,,,,,,,,,,,,,,,,,
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11,-53.5,-48.5,-42.5,-48.5,-53.5,-55.0,1303.30
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04,-52.5,-44.5,-38.5,-42.5,-47.5,-55.0,1309.00
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11,-51.5,-40.5,-33.5,-36.5,-41.5,-60.0,1315.00
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03,-48.5,-44.5,-35.5,-39.5,-44.5,-55.0,1308.00
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09,-51.5,-46.5,-37.5,-43.5,-50.5,-60.0,1302.75
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02,-51.5,-46.5,-35.5,-43.5,-51.5,-60.0,1304.00
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02,-43.5,-45.5,-35.5,-43.5,-51.5,-60.0,1300.50
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00,-39.5,-48.5,-40.5,-49.5,-55.5,-60.0,1307.00
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02,-37.5,-43.5,-37.5,-46.5,-54.5,-55.0,1297.00
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03,-44.5,-50.5,-44.5,-50.5,-58.5,-60.0,1306.00
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09,-39.5,-46.5,-39.5,-44.5,-52.5,-55.0,1313.50
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07,-36.5,-44.5,-37.5,-40.5,-47.5,-55.0,1311.00
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02,-38.5,-49.5,-41.5,-44.5,-51.5,-60.0,1314.70
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03,-39.5,-51.5,-45.5,-48.5,-58.5,-50.0,1326.75
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02,-44.5,-53.5,-47.5,-51.5,-59.5,-60.0,1335.40
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03,-50.5,-55.5,-49.5,-50.5,-58.5,-55.0,1343.25
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04,-54.5,-57.5,-52.5,-55.5,-64.5,-50.0,1339.00
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22,-66.5,-61.5,-54.5,-53.5,-58.5,-45.0,1340.50
2022-08-26,0.01,0.02,0.02,0.03,0.01,0.01,0.08,0.09,0.10,0.10,-66.5,-55.5,-47.5,-46.5,-49.5,-50.0,1334.50

In [93]:
df_6 = df_6.sort_index()
df_6

            국고1년  국고3년  국고5년  통안364일  통안2년
DateTime
2022-08-01  2.92  3.08  3.13    3.00  3.07
2022-08-02  2.89  3.01  3.04    2.97  3.01
2022-08-03  2.90  3.06  3.10    2.97  3.08
2022-08-04  2.89  3.11  3.13    2.94  3.10
2022-08-05  2.87  3.07  3.09    2.89  3.07
2022-08-08  2.90  3.13  3.15    2.92  3.12
2022-08-09  2.89  3.13  3.15    2.91  3.11
2022-08-10  2.90  3.15  3.18    2.92  3.14
2022-08-11  2.89  3.12  3.17    2.90  3.12
2022-08-12  2.90  3.18  3.23    2.92  3.14
2022-08-16  2.86  3.07  3.12    2.86  3.04
2022-08-17  2.88  3.08  3.14    2.88  3.06
2022-08-18  2.88  3.12  3.18    2.90  3.08
2022-08-19  2.92  3.19  3.27    2.93  3.14
2022-08-22  2.96  3.24  3.31    2.85  3.19
2022-08-23  2.99  3.25  3.28    2.98  3.24
2022-08-24  3.04  3.31  3.39    3.03  3.28
2022-08-25  3.19  3.53  3.59    3.20  3.50

In [94]:
df_6 = df_6.sort_index()

In [95]:
join_data_220828 = pd.concat([join , df_6], axis=1)
join_data_220828

,대비_irs_1Y,대비_irs_2Y,대비_irs_3Y,대비_irs_5Y,대비_irs_10Y,대비_crs_1Y,대비_crs_2Y,대비_crs_3Y,대비_crs_5Y,대비_crs_10Y,...,베이시스_3Y,베이시스_5Y,베이시스_10Y,Swap Point,ndf_mid,국고1년,국고3년,국고5년,통안364일,통안2년
DateTime,,,,,,,,,,,,,,,,,,,,,
2022-08-01,0.03,0.07,0.06,0.06,0.08,0.10,0.09,0.10,0.10,0.11,...,-42.5,-48.5,-53.5,-55.0,1303.30,2.92,3.08,3.13,3.00,3.07
2022-08-02,-0.03,-0.08,-0.08,-0.09,-0.10,-0.02,-0.04,-0.04,-0.03,-0.04,...,-38.5,-42.5,-47.5,-55.0,1309.00,2.89,3.01,3.04,2.97,3.01
2022-08-03,0.03,0.05,0.05,0.05,0.05,0.04,0.09,0.10,0.11,0.11,...,-33.5,-36.5,-41.5,-60.0,1315.00,2.90,3.06,3.10,2.97,3.08
2022-08-04,0.01,0.06,0.06,0.06,0.06,0.04,0.02,0.04,0.03,0.03,...,-35.5,-39.5,-44.5,-55.0,1308.00,2.89,3.11,3.13,2.94,3.10
2022-08-05,-0.02,-0.04,-0.05,-0.04,-0.03,-0.05,-0.06,-0.07,-0.08,-0.09,...,-37.5,-43.5,-50.5,-60.0,1302.75,2.87,3.07,3.09,2.89,3.07
2022-08-08,0.04,0.05,0.04,0.04,0.03,0.04,0.05,0.06,0.04,0.02,...,-35.5,-43.5,-51.5,-60.0,1304.00,2.90,3.13,3.15,2.92,3.12
2022-08-09,0.00,0.02,0.00,-0.01,-0.02,0.08,0.03,0.00,-0.01,-0.02,...,-35.5,-43.5,-51.5,-60.0,1300.50,2.89,3.13,3.15,2.91,3.11
2022-08-10,0.02,0.03,0.05,0.05,0.04,0.06,0.00,0.00,-0.01,0.00,...,-40.5,-49.5,-55.5,-60.0,1307.00,2.90,3.15,3.18,2.92,3.14
2022-08-11,-0.02,-0.03,-0.02,0.00,0.01,0.00,0.02,0.01,0.03,0.02,...,-37.5,-46.5,-54.5,-55.0,1297.00,2.89,3.12,3.17,2.90,3.12
2022-08-12,0.02,0.04,0.05,0.06,0.07,-0.05,-0.03,-0.02,0.02,0.03,...,-44.5,-50.5,-58.5,-60.0,1306.00,2.90,3.18,3.23,2.92,3.14
2022-08-16,-0.05,-0.11,-0.12,-0.14,-0.15,0.00,-0.07,-0.07,-0.08,-0.09,...,-39.5,-44.5,-52.5,-55.0,1313.50,2.86,3.07,3.12,2.86,3.04
2022-08-17,0.01,0.02,0.02,0.02,0.02,0.04,0.04,0.04,0.06,0.07,...,-37.5,-40.5,-47.5,-55.0,1311.00,2.88,3.08,3.14,2.88,3.06
2022-08-18,0.00,0.05,0.04,0.05,0.06,-0.02,0.00,0.00,0.01,0.02,...,-41.5,-44.5,-51.5,-60.0,1314.70,2.88,3.12,3.18,2.90,3.08
2022-08-19,0.02,0.05,0.07,0.08,0.10,0.01,0.03,0.03,0.04,0.03,...,-45.5,-48.5,-58.5,-50.0,1326.75,2.92,3.19,3.27,2.93,3.14
2022-08-22,0.03,0.04,0.05,0.05,0.03,-0.02,0.02,0.03,0.02,0.02,...,-47.5,-51.5,-59.5,-60.0,1335.40,2.96,3.24,3.31,2.85,3.19
2022-08-23,0.05,0.05,0.05,0.03,0.02,-0.01,0.03,0.03,0.04,0.03,...,-49.5,-50.5,-58.5,-55.0,1343.25,2.99,3.25,3.28,2.98,3.24
2022-08-24,0.05,0.07,0.07,0.08,0.10,0.01,0.05,0.04,0.03,0.04,...,-52.5,-55.5,-64.5,-50.0,1339.00,3.04,3.31,3.39,3.03,3.28
2022-08-25,0.18,0.20,0.21,0.20,0.16,0.06,0.16,0.19,0.22,0.22,...,-54.5,-53.5,-58.5,-45.0,1340.50,3.19,3.53,3.59,3.20,3.50
2022-08-26,0.01,0.02,0.02,0.03,0.01,0.01,0.08,0.09,0.10,0.10,...,-47.5,-46.5,-49.5,-50.0,1334.50,NaN,NaN,NaN,NaN,NaN

In [97]:
join_data_220828 = join_data_220828.dropna()

In [98]:
join_data_220828.isna().sum()

대비_irs_1Y     0
대비_irs_2Y     0
대비_irs_3Y     0
대비_irs_5Y     0
대비_irs_10Y    0
대비_crs_1Y     0
대비_crs_2Y     0
대비_crs_3Y     0
대비_crs_5Y     0
대비_crs_10Y    0
베이시스_1Y       0
베이시스_2Y       0
베이시스_3Y       0
베이시스_5Y       0
베이시스_10Y      0
Swap Point    0
ndf_mid       0
국고1년          0
국고3년          0
국고5년          0
통안364일        0
통안2년          0
dtype: int64

In [99]:
join_data_220828.to_excel('./xlsx/join_data_220828.xlsx')

In [100]:
join_data_220828.columns

Index(['대비_irs_1Y', '대비_irs_2Y', '대비_irs_3Y', '대비_irs_5Y', '대비_irs_10Y',
       '대비_crs_1Y', '대비_crs_2Y', '대비_crs_3Y', '대비_crs_5Y', '대비_crs_10Y',
       '베이시스_1Y', '베이시스_2Y', '베이시스_3Y', '베이시스_5Y', '베이시스_10Y', 'Swap Point',
       'ndf_mid', '국고1년', '국고3년', '국고5년', '통안364일', '통안2년'],
      dtype='object')